services:
  api:
    container_name: api
    build:
      context: .
    ports:
      - 8084:8084
    depends_on:
      db:
        condition: service_healthy
  db:
    container_name: db
    image: mysql:latest
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin --user=root --password=root --host=localhost ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: concessionaria
    ports:
      - 3307:3306
